package mate.academy.hibernate.relations.dao.impl;

import java.util.Optional;
import mate.academy.hibernate.relations.dao.AbstractTest;
import mate.academy.hibernate.relations.dao.CountryDao;
import mate.academy.hibernate.relations.model.Country;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class CountryDaoImplTest extends AbstractTest {
    public static final Country usa = new Country("USA");
    public static final Country ukraine = new Country("Ukraine");

    @Override
    protected Class<?>[] entities() {
        return new Class[] {Country.class};
    }

    @Test
    public void create_Ok() {
        CountryDao countryDao = new CountryDaoImpl(getSessionFactory());
        verifyCreateCountryWorks(countryDao, usa.clone(), 1L);
        verifyCreateCountryWorks(countryDao, ukraine.clone(), 2L);
    }

    @Test
    public void getById_Ok() {
        CountryDao countryDao = new CountryDaoImpl(getSessionFactory());
        verifyCreateCountryWorks(countryDao, usa.clone(), 1L);
        Optional<Country> usaOptional = countryDao.get(1L);
        Assertions.assertTrue(usaOptional.isPresent());
        Country actualUsa = usaOptional.get();
        Assertions.assertNotNull(actualUsa);
        Assertions.assertEquals(1L, actualUsa.getId());
        Assertions.assertEquals(usa.getName(), actualUsa.getName());

        verifyCreateCountryWorks(countryDao, ukraine.clone(), 2L);
        Optional<Country> ukraineOptional = countryDao.get(2L);
        Assertions.assertTrue(ukraineOptional.isPresent());
        Country actualUkraine = ukraineOptional.get();
        Assertions.assertNotNull(actualUkraine);
        Assertions.assertEquals(2L, actualUkraine.getId());
        Assertions.assertEquals(ukraine.getName(), actualUkraine.getName());
    }

    @Test
    public void getByNotExistingId_Ok() {
        CountryDao countryDao = new CountryDaoImpl(getSessionFactory());
        Optional<Country> actual = countryDao.get(100L);
        Assertions.assertFalse(actual.isPresent());
    }

    static void verifyCreateCountryWorks(CountryDao countryDao, Country country, Long expectedId) {
        Country actual = countryDao.add(country);
        Assertions.assertNotNull(actual, "Check you have implemented the `create` method "
                + "in the CountryDaoImpl class");
        Assertions.assertNotNull(actual.getId(), "ID for country should be autogenerated");
        Assertions.assertEquals(expectedId, actual.getId());
        Assertions.assertEquals(country.getName(), actual.getName());
    }
}
